#!/bin/bash

choice() {
  echo "Select search engine:"
  echo "1. Google"
  echo "2. DuckDuckGo"
  echo "3. Exit"
  read -p "Enter your choice (1/2/3): " choice

  case $choice in
  1)
    selected_engine="https://google.com/search?q="
    ;;
  2)
    selected_engine="https://duckduckgo.com/?q="
    ;;
  3)
    echo "Exiting program"...
    exit
    ;;
  *)
    echo "Invalid choice. Please select 1 or 2."
    ;;
  esac
}

selected_engine=""
choice 

while true; do
  printf "exit to interrupt\nselect to re-select search engine\n\n"
  read -p "Enter query: " query

  if [[ $query == "exit" ]]; then
    echo "Exiting program."
    break
  elif [[ $query == "select" ]]; then
    choice
    continue
  fi

  if [[ -z $query ]]; then
    echo "Query cannot be empty."
    continue
  fi

  printf "\033c"
  firefox "${selected_engine}$(echo $query | sed 's/ /+/g')" &
done