#!/bin/bash

# TODO // MAKE IT READ .ENV FILE SAVED VARIABLE

browser(){
  printf "\033c"
  printf "Please select your preferred browser (saved to memory)\n"
  printf "1. Firefox (recommended)\n2. Google Chrome\n3. Microsoft Edge\n"
  read -p "" prefBrowser
}

choice() {
  printf "\033c"
  printf "Select search engine:\n"
  printf "1. Google\n"
  printf "2. DuckDuckGo\n"
  printf "3. Bing\n"
  printf "4. Exit\n"
  read -p "Enter your choice (1/2/3/4): " choice

  case $choice in
  1)
    selected_engine="https://google.com/search?q="
    ;;
  2)
    selected_engine="https://duckduckgo.com/?q="
    ;;
  3)
    selected_engine="https://bing.com/search?q="
    ;;
  4)
    printf "Exiting program"...
    exit
    ;;
  *)
    printf "Invalid choice. Please select a valid choice."
    ;;
  esac
}

selected_engine=""
browser
choice 

while true; do
  printf "exit to interrupt\nselect to re-select search engine\n\n"
  read -p "Enter query: " query

  if [[ $query == "exit" ]]; then
    printf "Exiting program."
    break
  elif [[ $query == "select" ]]; then
    choice
    continue
  fi

  if [[ -z $query ]]; then
    printf "Query cannot be empty."
    continue
  fi

  printf "\033c"

  case "$prefBrowser" in
    1)
      firefox "${selected_engine}$(printf $query | sed 's/ /+/g')" &
      ;;
    2)
      chrome "${selected_engine}$(printf $query | sed 's/ /+/g')" &
      ;;
    3)
      microsoft-edge "${selected_engine}$(printf $query | sed 's/ /+/g')" &
      ;;
    *)
      printf "Error"
      exit 1
      ;;
esac
done