#!/bin/bash

#this is so utterly dumb

urlencode() {
    local raw="$1"
    local encoded=""
    local char

    for ((i = 0; i < ${#raw}; i++)); do
        char="${raw:i:1}"
        case "$char" in
        [a-zA-Z0-9.~_-])
            encoded+="$char"
            ;;
        ' ')
            encoded+='+'
            ;;
        *)
            printf -v encoded '%s%%%02X' "$encoded" "'$char"
            ;;
        esac
    done

    echo "$encoded"
}
